# Global settings applied to the whole site.
[build]
  publish = "public"
  command = "hugo"
  [build.environment]
    HUGO_VERSION = "0.31"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "hugo"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
#
# The below command sets the baseURL of the hugo site to
# https://branch--sitename.netlify.com for testing
[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --buildDrafts"